version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    environment:
      - JENKINS_OPTS=--prefix=/jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # 挂载宿主机的 Docker socket，使 Jenkins 可以运行 Docker 命令
      - /etc/timezone:/etc/timezone  # 挂载宿主机的时区文件
      - /etc/localtime:/etc/localtime  # 挂载宿主机的本地时间配置
    ports:
      - "8080:8080"
      - "50000:50000"  # 用于 Jenkins Agent 的连接
    restart: unless-stopped
    networks:
      - jenkins_network

volumes:
  jenkins_home:
    driver: local  # 持久化 Jenkins 数据目录

networks:
  jenkins_network:
    driver: bridge

